### ISSUE TITLE
Вопрос: Какую приватность надо настроить?

### ISSUE THREAD

**Issue by en0tuk** [bewflast/VK-Music-Discord-RPC#1]
Какую приватность надо настроить и как, чтоб работала программа

**Comment by bewflast** [comment]
Привет, в ВК нужно включить трансляцию аудио на твою страницу:
![](https://i.imgur.com/cFmfCqW.png)

Разрешить неавторизованным пользователям просматривать твою страницу (приватность, самый низ):
![](https://i.imgur.com/Kt2f16G.png)

В Дискорде включить отображение статуса текущей активности:
![](https://i.imgur.com/23j4O3J.png)

Скачать бинарник [отсюда](https://github.com/bewflast/VK-Music-Discord-RPC/releases/tag/Latest), либо собрать самостоятельно.
После запуска ввести ссылку на свою страницу ( пример: httрs://vk.com/user )

**Comment by bewflast** [comment]
@en0tuk дай знать, если я решил твою проблему
